elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]
  username: "kibana_system"
  password: "eJL-r*4rNjRioOwWPEMT"

server:
  name: kibana
  host: "0.0.0.0"
  ssl:
    enabled: false

xpack:
  encryptedSavedObjects:
    encryptionKey: "anotherExtremelyExtremelySecureKeyThatIsLong!"

  apm:
    ui:
      enabled: true
    serviceMapEnabled: true

  fleet:
    agents:
      enabled: true
    packages:
      - name: apm
        version: latest
