# Usa immagine base Node.js LTS
FROM node:20

# Crea e imposta la working directory
WORKDIR /app/server

# Copia i file package.json e package-lock.json
COPY server/package*.json ./

# Installa le dipendenze (anche dev)
RUN npm install

# Copia tutto il codice del server
COPY server/ .

# Espone la porta del server (definita anche in .env)
EXPOSE 3000

# Avvio automatico in base alla variabile NODE_ENV
CMD [ "sh", "-c", "if [ \"$NODE_ENV\" = 'development' ]; then npm run dev; else npm start; fi" ]