# Fase 1: build Vite
FROM node:20 AS builder

WORKDIR /app/client

COPY client/package*.json ./
RUN npm install
COPY client/ .
RUN npm run build

# Fase 2: serve con NGINX
FROM nginx:alpine

COPY --from=builder /app/client/dist /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf