version: "3.9"

networks:
  internal_net:
    name: internal_net
    internal: true

  proxy_net:
    name: proxy_net
    driver: bridge

  frontend_net:
    name: frontend_net
    driver: bridge

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    networks:
      - proxy_net
      - frontend_net
    ports:
      - "80:80"
    env_file:
      - docker/env/.env
    volumes:
      - ${NGINX_CONFIG}:/etc/nginx/nginx.conf:ro
      - ./proxy/certs:/etc/nginx/certs:ro
      - ./proxy/proxy_params:/etc/nginx/proxy_params:ro

      - ./docker/volumes/proxy-logs:/var/log/nginx:delegated

      - ./frontend/dist:/var/www/frontend:ro
    depends_on:
      - server
      - frontend

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    networks:
      - internal_net
      - proxy_net
    env_file:
      - docker/env/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./server/public:/app/public:ro
      - ./server:/app:delegated
    expose:
      - "3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - frontend_net
    expose:
      - "80"
    depends_on:
      - server

  db:
    image: mongo:latest
    container_name: db
    networks:
      - internal_net
    expose:
      - "27017"
    volumes:
      - ./docker/volumes/mongodb:/data/db:delegated
      - ./docker/init-db:/docker-entrypoint-initdb.d:ro
