FROM node:20

COPY sandbox-client/package*.json .

# Installazione forzata di vite@4.4.9 come devDependency + tutte le dipendenze
RUN npm install vite@4.4.9 --save-dev && npm install

EXPOSE 5173

CMD ["npx", "vite", "--host"]